### ISSUE TITLE
update epubcheck to 4.2.2

### ISSUE THREAD

**Issue by pkra** [chialab/epubchecker#1]
https://github.com/chialab/epubchecker/blob/8e0b2cfdc414940fad5efcba37ff530df6ce2175/package.json#L4

While https://github.com/w3c/epubcheck/releases/tag/v4.2.2 is the latest release.

**Comment by pkra** [comment]
I'd be happy to make a PR.

**Comment by edoardocavazza** [comment]
Hello @pkra, thank you for reporting it!

If you can create a PR for that, I will merge it as soon as possibile!

**Comment by pkra** [comment]
@edoardocavazza done. I wasn't completely sure on commit message formatting; let me know if it needs changing.
