### ISSUE TITLE
question on checking a folder

### ISSUE THREAD

**Issue by pkra** [chialab/epubchecker#3]
I have a question about passing a folder to epubchecker.js. 

In

https://github.com/chialab/epubchecker/blob/a7da8172abf0a3c1a0133c4ccd580c5b24f40182/lib/index.js#L169-L175

epubchecker creates an epub file and then runs epubcheck on that file.

I'm wondering if there is a specific reason why it is not using epubcheck's expanded mode (--mode exp) instead. The current behavior was surprising (for me anyway) and seems less performant.

**Comment by edoardocavazza** [comment]
Probably because I had totally missed the expanded mode when looking at the epubcheck documentation 😣Thanks for the suggestion! I will prepare a PR later today!

**Comment by pkra** [comment]
Thanks for the quick reply, @edoardocavazza.

>  I will prepare a PR later today!

That'd be great -- thanks!

**Comment by edoardocavazza** [comment]
Hi @pkra! I have created the [PR](https://github.com/chialab/epubchecker/pull/4) if you would like to give it try it 😉

**Comment by pkra** [comment]
@edoardocavazza thanks so much for the fast fix! 

For what it's worth, epubFromDirectory.js seemed like a useful separate library.
